CREATE TABLE USR (
  USR_AIC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  USR_NM VARCHAR(255) NOT NULL,
  USR_CPF CHAR(11) NOT NULL,
  USR_EML VARCHAR(100) NOT NULL,
  USR_SENHA VARCHAR(255) NOT NULL,
  USR_ATV TINYINT(1) NOT NULL DEFAULT 1,

  USR_A_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USR_A_UPDATE  TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  USR_A_LOGIN   TIMESTAMP NULL,

  UNIQUE KEY UQ_USR_CPF (USR_CPF),
  UNIQUE KEY UQ_USR_EML (USR_EML)
);